version: "3.8"
services:
  server:
    build: .
    command: /udptcp -s -H 0.0.0.0 -p 8080
    volumes:
      - ${PWD}/share:/share:ro
  client:
    build: .
    command: sh /share/client-wrapper.sh server 8080 5
    volumes:
      - ${PWD}/share:/share:ro
  test:
    image: gaiaadm/pumba
    command: -i 20s netem -d 10s ${PUMBA_MODE} udptcp_server_1 udptcp_client_1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
